# Generated by forge sync for Forge v1.2.7; forge sync rewrites it. Host hooks source it.
for folder in /usr/local/bin /opt/homebrew/bin "$HOME/.local/bin" "$XDG_BIN_HOME" "$UV_TOOL_BIN_DIR"; do
  [ -d "$folder" ] && PATH="$folder:$PATH"
done
export PATH
if command -v forge >/dev/null 2>&1; then :
elif command -v uvx >/dev/null 2>&1; then
  forge() { uvx -q --from git+https://github.com/knacklabs/symphony-forge@v1.2.7 forge "$@"; }
else
  forge() { echo "Forge isn't installed, so this hook can't run; install it with uv tool install git+https://github.com/knacklabs/symphony-forge@v1.2.7, then run forge doctor." >&2; return 2; }
fi
