"""The git hooks. pre-commit keeps commits on Forge's own branches and fixes small; pre-push keeps
the default branch pull-request-only and catches fix commits made with --no-verify."""
from __future__ import annotations

import argparse
import json
import sys
from fnmatch import fnmatchcase
from pathlib import Path
from typing import Any

from forge import repo, task
from forge.repo import git, refuse, run

LIMIT = 5  # code files a fix may change before it has to become a story

# Each host's hook file: event -> (the tools it matches, or None for all; the forge hook it runs).
HOSTS = {
    ".claude/settings.json": {"SessionStart": (None, "context"), "PreCompact": (None, "handoff"),
                              "PreToolUse": ("Bash", "deny"),
                              "PostToolUse": ("ExitPlanMode|AskUserQuestion", "approval")},
    ".codex/hooks.json": {"SessionStart": (None, "context"), "PreCompact": (None, "handoff"),
                          "PreToolUse": ("Bash", "deny"),
                          "PostToolUse": ("request_user_input", "approval")},
}
# Claude ignores a repo-level bypass mode, so the repo pre-allows the tools Forge's full access
# means; the deny hook above still runs first and blocks destructive commands.
ALLOW = {".claude/settings.json": ["Bash", "Edit", "Write", "WebFetch", "WebSearch"]}

SHIM_MARK = "# Generated by forge sync"
# The hook that was there before Forge runs first, with the same arguments and input.
SHIM = """\
#!/bin/sh
# Generated by forge sync for Forge <version>; forge sync rewrites it. It is never committed.
if [ -x "$0.pre-forge" ]; then
  input=$(mktemp) || exit 1
  cat > "$input"
  <run-prior> < "$input" || { status=$?; rm -f "$input"; exit "$status"; }
  exec < "$input"
  rm -f "$input"
fi
command -v forge >/dev/null 2>&1 && exec forge hook <hook> "$@"
echo "Forge isn't installed, so git can't check this <what>." >&2
echo "Next: <install>" >&2
exit 1
"""


def shims(top: Path, cfg: dict[str, Any]) -> dict[Path, str]:
    """The two git hook shims, in the hooks folder every worktree shares."""
    from forge import sync

    folder = Path(repo.git("rev-parse", "--path-format=absolute", "--git-path", "hooks", cwd=top))
    wanted = {}
    for hook, what in (("pre-commit", "commit"), ("pre-push", "push")):
        path = folder / hook
        prior = sync.read(path.with_name(f"{hook}.pre-forge")) or sync.read(path)
        husky = ('. "$(dirname "$0")/h"' in prior or
                 ('n=$(basename "$0")' in prior and
                  's=$(dirname "$(dirname "$0")")/$n' in prior))
        run_prior = ('sh -c \'. "$0.pre-forge"\' "$0" "$@"' if husky
                     else '"$0.pre-forge" "$@"')
        wanted[path] = (SHIM.replace("<version>", cfg["version"]).replace("<hook>", hook)
                        .replace("<what>", what).replace("<install>", sync.install_line(cfg["version"]))
                        .replace("<run-prior>", run_prior))
    return wanted


def ships(top: Path, cfg: dict[str, Any]) -> dict[str, str]:
    from forge import sync

    return {
        "AGENTS.md": sync._agents(top),
        **({"CLAUDE.md": ""} if (top / "CLAUDE.md").exists() or (top / "CLAUDE.md").is_symlink()
           else {}),  # a dangling link counts too
        **{rel: sync._hooks(top, rel, events, ALLOW.get(rel, [])) for rel, events in HOSTS.items()},
        ".codex/config.toml": sync._codex_config(top),
    }

REFUSALS = {
    "not_forge": ("{branch} was not started by Forge, so it has no story, task or fix.",
                  'forge fix start "<why>" --done "<done when>"'),
    "promote": ("Fix {fix} {problem}, so it has to become a story, unless the human allows it "
                "with forge fix allow-large.", "forge story new <KEY> --from-fix {fix}"),
    "push_default": ("{branch} changes only through a merged pull request, so this push is refused.",
                     "forge close <item>"),
}


def pre_commit(args: argparse.Namespace) -> None:
    top = repo.root()
    branch = repo.current_branch(top)
    if branch == repo.default_branch(top):
        refuse(repo.REFUSALS["default_branch"], branch=branch)
    found = task.branch_item(branch, top) if branch else None
    if found is None:
        refuse(REFUSALS["not_forge"], branch=branch or "A detached HEAD")
    item, state = found
    if branch.startswith(("fix/", "forge/")):
        # Finishing a merge: the default branch's changes coming in don't count against the fix.
        merging = ["MERGE_HEAD"] if run("git", "rev-parse", "-q", "--verify", "MERGE_HEAD").returncode == 0 else []
        _promote(item, state, repo.config(top), _base("HEAD", *merging), "")


def pre_push(args: argparse.Namespace) -> None:
    default = repo.default_branch()
    for line in sys.stdin.read().splitlines():
        _, sha, remote_ref = (line.split() + ["", "", ""])[:3]
        if remote_ref == f"refs/heads/{default}":
            refuse(REFUSALS["push_default"], branch=default)
        # The destination names the fix, whatever the source: a branch, a tag or a commit ID.
        kind, _, fix = remote_ref.removeprefix("refs/heads/").partition("/")
        if kind not in ("fix", "forge") or set(sha) == {"0"}:  # a deletion pushes no commits
            continue
        match = repo.ITEM.fullmatch(fix)
        state = task.show(sha, repo.state_path(fix)) if match and match["fix"] else None
        # The pushed commit's own state decides; without one there is no allow-large reason.
        _promote(fix, json.loads(state) if state else {}, repo.config(), _base(sha), sha)


def _base(*tips: str) -> str:
    """Where a fix's own changes start: its merge base with the default branch."""
    default = repo.default_branch()
    remote = f"origin/{default}"
    main = remote if run("git", "rev-parse", "-q", "--verify", remote).returncode == 0 else default
    # With several tips, git takes the merge base with a merge of all of them.
    return git("merge-base", main, *tips)


def _promote(fix: str, state: dict[str, Any], cfg: dict[str, Any], base: str, head: str) -> None:
    """Refuse a fix over the limit or touching an interface, unless the human allowed it.
    head "" means the staged changes."""
    if state.get("allow_large"):
        return
    diff = (base, head) if head else ("--cached", base)
    changed = git("diff", "--name-only", "--no-renames", "-z", *diff).split("\0")
    interfaces = cfg["interfaces"]
    # Markdown, state and planning documents never count.
    code = [path for path in changed if path and not (
        path.lower().endswith(".md") or path.startswith((".factory/", "plans/")))]
    # ponytail: "**/" also matches zero folders by trying the pattern without it.
    touched = [path for path in code if any(
        fnmatchcase(path, glob) or fnmatchcase(path, glob.replace("**/", "")) for glob in interfaces)]
    if touched:
        refuse(REFUSALS["promote"], fix=fix, problem=f"changes the interface {touched[0]}")
    # Test files and forge sync's own output don't count toward the size.
    tests = git("diff", "--name-only", "--no-renames", "-z", *diff, "--", *repo.TEST_PATHS)
    code = [path for path in code if path not in tests.split("\0")]
    if len(code) > LIMIT:
        from forge import sync

        output = sync.synced(repo.root(), cfg, base, head, code)
        code = [path for path in code if path not in output]
    if len(code) > LIMIT:
        refuse(REFUSALS["promote"], fix=fix,
               problem=f"changes {len(code)} code files, over the limit of {LIMIT}")


COMMANDS = [
    {"words": "hook pre-commit", "run": "pre_commit", "changes_state": False,
     "help": "The git pre-commit rules", "args": [], "position": 270,
     "listing": "| `forge hook pre-commit` | The git pre-commit rules |"},
    {"words": "hook pre-push", "run": "pre_push", "changes_state": False,
     "help": "The git pre-push rules", "args": [], "position": 280,
     "listing": "| `forge hook pre-push` | The git pre-push rules |"},
]
