"""forge-pr-check: the required pull request check, run from a checkout of the base branch.

Policy and config come from the base checkout. The pull request head is data only: its files are
read through git and never run, imported or checked out.
"""
from __future__ import annotations

import argparse
import json
import re
from fnmatch import fnmatch
from pathlib import Path
from typing import Any

from forge import repo, review

REFUSALS = {
    "usage": ("forge hook pr-check needs the pull request's --base, --head and --branch.",
              "forge hook pr-check --base <base commit> --head <head commit> --branch <branch>"),
    "not_started": ("Forge did not start {branch}: no task or fix at its head is on that branch.",
                    'forge fix start "<why>" --done "<done when>"'),
    "fix_line": ("The fix on {branch} has no {line} line.",
                 'forge fix start "<why>" --done "<done when>"'),
    "promote": ("The fix on {branch} {problem}, and has no allow-large reason.",
                'forge story new <KEY> --from-fix {fix} (or, with the human\'s permission, '
                'forge fix allow-large "<reason>")'),
    "not_reviewed": ("The committed review at the head of {branch} is {problem}.",
                     "forge close {item}"),
    "story_doc": ("{problem}", "fix the story doc, then forge read <KEY>"),
}
CODE_LIMIT = 5
WORKFLOW_PATH = ".github/workflows/forge.yml"

# tests checks the pull request's own code. forge-pr-check runs from the base branch
# (pull_request_target), so a pull request can't change the check that judges it. In Forge's
# own repo that base checkout is the Forge to install, so close and the check fingerprint alike.
WORKFLOW = """\
# Generated by forge sync for Forge <version>; forge sync rewrites it.
name: forge

on:
  pull_request:
  pull_request_target:

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' || github.event_name == 'pull_request_target' }}

permissions:
  contents: read
  actions: read

jobs:
  tests:
    # Each event runs one of the two jobs. The skipped one takes another name, because a
    # skipped job would otherwise pass a required check of the same name.
    if: github.event_name == 'pull_request'
    name: ${{ github.event_name == 'pull_request' && 'tests' || 'tests (other event)' }}
    runs-on: <runner>
    env:
      UV_FROZEN: '1'
<tests-timeout>    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v6
        with:
          python-version: '3.11'
      - uses: astral-sh/setup-uv@v6
      - id: parent-tests
        env:
          GH_TOKEN: ${{ github.token }}
          HEAD_SHA: ${{ github.event.pull_request.head.sha || github.sha }}
          BASE_SHA: ${{ github.event.pull_request.base.sha }}
        run: python .forge/review-tests.py
<node>      - run: <test>
        if: steps.parent-tests.outputs.reuse != 'true'

  forge-pr-check:
    if: github.event_name == 'pull_request_target'
    name: ${{ github.event_name == 'pull_request_target' && 'forge-pr-check' || 'forge-pr-check (other event)' }}
    runs-on: <runner>
    steps:
      # The base branch's code and forge.toml; the pull request's commits are only data.
      - uses: actions/checkout@v7
        with:
          ref: ${{ github.event.pull_request.base.sha }}
          fetch-depth: 0
      - uses: actions/setup-python@v6
        with:
          python-version: '3.11'
      - uses: astral-sh/setup-uv@v6
      - env:
          PR: ${{ github.event.pull_request.number }}
          BASE_SHA: ${{ github.event.pull_request.base.sha }}
          HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        run: |
          git fetch --no-tags origin "refs/pull/$PR/head"
          test "$(git rev-parse FETCH_HEAD)" = "$HEAD_SHA"
<choose>      - run: <install>
      - env:
          BASE_SHA: ${{ github.event.pull_request.base.sha }}
          HEAD_SHA: ${{ github.event.pull_request.head.sha }}
          HEAD_REF: ${{ github.event.pull_request.head.ref }}
        run: forge hook pr-check --base "$BASE_SHA" --head "$HEAD_SHA" --branch "$HEAD_REF"
      - name: Report pull request size
        if: always()
        continue-on-error: true
        env:
          BASE_SHA: ${{ github.event.pull_request.base.sha }}
          HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        run: |
          stats=$(git diff --numstat "$BASE_SHA...$HEAD_SHA")
          echo "$stats" | awk '{a += $1; d += $2} END {printf "Net lines: %+d (%d added, %d removed)\\n", a - d, a, d}' >> "$GITHUB_STEP_SUMMARY"
"""

# A client's check runs the Forge release its default branch pins. A pull request that changes
# that pin (an upgrade) is checked by the release it pins instead, installed from Forge's own
# repo by its tag. The pin is read through git and parsed as TOML, and must look like a release
# before it is used; nothing from the pull request runs.
CHOOSE = r"""          pin() {
            git show "$1:forge.toml" | python3 -c '
          import sys, tomllib
          try:
              print(tomllib.load(sys.stdin.buffer).get("version", ""))
          except tomllib.TOMLDecodeError as problem:
              sys.exit(f"forge.toml in this pull request is not valid TOML: {problem}. Fix it, then push again.")'
          }
          release=$(pin "$HEAD_SHA")
          if [ "$release" = "$(pin "$(git merge-base "$BASE_SHA" "$HEAD_SHA")")" ]; then
            release="<version>"
          elif [[ ! "$release" =~ ^v?[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "This pull request sets Forge's version in forge.toml to \"$release\", which isn't a Forge release such as v1.2.0. Set it to a Forge release, then push again." >&2
            exit 1
          fi
          echo "FORGE_RELEASE=$release" >> "$GITHUB_ENV"
"""


def ships(top: Path, cfg: dict[str, Any]) -> dict[str, str]:
    from forge import sync

    node = ""
    if (top / "package.json").is_file() or re.search(r"\b(?:npm|npx|pnpm|yarn|node)\b", cfg["test"]):
        node = ("      - uses: actions/setup-node@v7\n"
                "        if: steps.parent-tests.outputs.reuse != 'true'\n")
        version_file = next((name for name in (".nvmrc", ".node-version")
                             if (top / name).is_file()), None)
        if version_file:
            node += f"        with:\n          node-version-file: {version_file}\n"
        else:
            package = json.loads(sync.read(top / "package.json") or "{}")
            version = package.get("engines", {}).get("node")
            version = version if isinstance(version, str) and version.strip() else "22"
            node += f"        with:\n          node-version: {json.dumps(version)}\n"
    source = cfg.get("repo") == "forge-source"
    workflow = (WORKFLOW.replace("<choose>", "" if source else CHOOSE)
                .replace("<version>", cfg["version"])
                .replace("<install>", "uv tool install ." if source
                         else sync.install_line("${FORGE_RELEASE#v}"))
                .replace("<tests-timeout>", "    timeout-minutes: 10\n"
                         if cfg.get("repo") == "client" and (top / "package.json").is_file()
                         else "")
                .replace("<node>", node)
                .replace("<test>", json.dumps(cfg["test"]))
                .replace("<runner>", json.dumps(cfg.get("runner", repo.DEFAULTS["runner"]))))
    if "tests" not in cfg.get("checks", []):
        start = workflow.index("  tests:\n")
        end = workflow.index("  forge-pr-check:\n")
        workflow = workflow[:start] + workflow[end:]
    return {WORKFLOW_PATH: workflow,
            ".forge/review-tests.py": (sync.TEMPLATES / "review-tests.py").read_text(encoding="utf-8")}


def pr_check(args: argparse.Namespace) -> int:
    # The workflow runs: forge hook pr-check --base <sha> --head <sha> --branch <head branch>
    given = dict(zip(args.args[::2], args.args[1::2]))
    if len(args.args) != 6 or set(given) != {"--base", "--head", "--branch"}:
        repo.refuse(REFUSALS["usage"])
    base, head, branch = given["--base"], given["--head"], given["--branch"]
    if not branch.startswith(("task/", "fix/", "story/", "forge/")):
        print("Forge didn't start this branch, so it checks nothing here; the repo's own CI and "
              "review apply.")
        return 0
    top = repo.root()
    cfg = repo.config(top)  # the base checkout's forge.toml, never the head's
    item, state = _started(top, head, branch)
    changed = repo.git("diff", "--name-only", f"{base}...{head}", cwd=top).splitlines()
    if "/" not in item:
        missing = [line for line, key in (("Why:", "why"), ("Done when:", "done_when"))
                   if not str(state.get(key) or "").strip()]
        if missing:
            repo.refuse(REFUSALS["fix_line"], branch=branch, line=" or ".join(missing))
        from forge import githooks

        fix_base = githooks.fix_base(top, state, base, head)
        own = repo.git("diff", "--name-only", "--no-renames", fix_base, head, cwd=top).splitlines()
        problem = "" if state.get("allow_large") else promote_problem(
            own, cfg["interfaces"], top, fix_base, head)
        if problem:
            repo.refuse(REFUSALS["promote"], branch=branch, problem=problem, fix=item)
    from forge import story

    doc_problem = story.check_pr_docs(top, head, changed)
    if doc_problem:
        repo.refuse(REFUSALS["story_doc"], problem=doc_problem)
    _check_specs(top, head, changed)
    result = state.get("review")
    if not (isinstance(result, dict) and isinstance(result.get("findings"), list)
            and isinstance(result.get("dismissals"), list)):
        problem = "missing"
    elif not _on_branch(top, str(result.get("commit", "")), head):
        problem = "for a commit that isn't part of this branch"
    elif result.get("changed") != review.fingerprint(head, item, top, state, base):
        problem = "out of date: the product files or what the change must do changed after it"
    elif review.blocking(result):
        problem = "blocked by serious findings no one fixed or dismissed"
    else:
        print(f"forge-pr-check passed for {branch}.")
        return 0
    repo.refuse(REFUSALS["not_reviewed"], branch=branch, problem=problem, item=item)


def _check_specs(top: Path, head: str, changed: list[str]) -> None:
    """Refuse an unconfirmed spec at head whose latest round of cold read had findings or which
    changed after it. A draft with no cold read yet, and a confirmed spec, keep today's rules."""
    from forge import story

    for path in dict.fromkeys(re.sub(r"\.read\.md$", ".md", path) for path in changed):
        slug = re.fullmatch(r"docs/specs/([a-z0-9]+(?:-[a-z0-9]+)*)\.md", path)
        text = story.show(top, head, path) if slug else None
        notes = story.show(top, head, f"docs/specs/{slug[1]}.read.md") if text is not None else None
        if notes is not None and story._record(text)[0].get("status") != "confirmed":
            story.gate(slug[1], path, notes, repo.git("rev-parse", f"{head}:{path}", cwd=top))


def promote_problem(changed: list[str], interfaces: list[str], top: Path, base: str,
                    head: str) -> str:
    """Why a fix must become a story, or "": it touches an interfaces path, or more than five code
    files. Markdown, .factory/, plans/, test files and forge sync's own output never count toward
    the five."""
    code = [path for path in changed
            if not path.lower().endswith(".md") and not path.startswith(review.BOOKKEEPING)]
    for path in code:
        # "/" + path lets "**/routes/**" match a top-level routes/ folder too.
        if any(fnmatch(path, pattern) or fnmatch("/" + path, pattern) for pattern in interfaces):
            return f"changes the interface path {path}"
    from forge import story, sync, worker

    tests = repo.git("diff", "--name-only", "--no-renames", base, head, "--", *worker.TEST_PATHS, cwd=top)
    code = [path for path in code if path not in tests.splitlines()]
    if len(code) > CODE_LIMIT:
        # Sync's output for the forge.toml the change pins: an upgrade's check runs that release.
        cfg = repo._config_text(story.show(top, head, "forge.toml") or "")
        output = sync.synced(top, cfg, base, head, code)
        code = [path for path in code if path not in output]
    if len(code) > CODE_LIMIT:
        return f"changes {len(code)} code files, over the limit of {CODE_LIMIT}"
    return ""


def _on_branch(top: Path, commit: str, head: str) -> bool:
    """The reviewed commit is the head or one of its ancestors. It is read from the head, so it
    must look like a commit id before it goes near git."""
    return bool(re.fullmatch(r"[0-9a-f]{40}|[0-9a-f]{64}", commit)) and repo.run(
        "git", "merge-base", "--is-ancestor", commit, head, cwd=top).returncode == 0


def _started(top: Path, head: str, branch: str) -> tuple[str, dict[str, Any]]:
    """The task or fix whose state at head names this branch."""
    # ponytail: reads every task and fix state at the head, one git call each; batch them
    # (git cat-file --batch) when a repo holds thousands.
    from forge import story

    listing = repo.git("ls-tree", "-r", "-z", "--name-only", head, "--", ".factory/stories",
                       ".factory/fixes", cwd=top)
    for path in listing.split("\0"):
        match = re.fullmatch(r"\.factory/(?:stories/([^/]+)/tasks/([^/]+)|fixes/([^/]+))\.json",
                             path)
        if not match:
            continue
        state = story.json_of(story.show(top, head, path))
        if state.get("branch") == branch:
            return (f"{match[1]}/{match[2]}" if match[1] else match[3]), state
    repo.refuse(REFUSALS["not_started"], branch=branch)


COMMANDS = [{
    "words": "hook pr-check", "run": "pr_check", "changes_state": False,
    "help": "The required forge-pr-check, run from the base branch",
    "args": [], "position": 290,
    "listing": "| `forge hook pr-check` | The required `forge-pr-check`, run in CI from the base branch |",
}]
