"""forge-pr-check: the required pull request check, run from a checkout of the base branch.

Policy and config come from the base checkout. The pull request head is data only: its files are
read through git and never run, imported or checked out.
"""
from __future__ import annotations

import argparse
import importlib
import json
import re
from fnmatch import fnmatch
from pathlib import Path
from typing import Any

from forge import repo, review

REFUSALS = {
    "usage": ("forge hook pr-check needs the pull request's --base, --head and --branch.",
              "forge hook pr-check --base <base commit> --head <head commit> --branch <branch>"),
    "not_started": ("Forge did not start {branch}: no task or fix at its head is on that branch.",
                    'forge fix start "<why>" --done "<done when>"'),
    "fix_line": ("The fix on {branch} has no {line} line.",
                 'forge fix start "<why>" --done "<done when>"'),
    "promote": ("The fix on {branch} {problem}, and has no allow-large reason.",
                'forge story new <KEY> --from-fix {fix} (or, with the human\'s permission, '
                'forge fix allow-large "<reason>")'),
    "not_reviewed": ("The committed review at the head of {branch} is {problem}.",
                     "forge close {item}"),
    "story_doc": ("{problem}", "fix the story doc, then forge read <KEY>"),
}
CODE_LIMIT = 5
WORKFLOW_PATH = ".github/workflows/forge.yml"

# tests checks the pull request's own code. forge-pr-check runs from the base branch
# (pull_request_target), so a pull request can't change the check that judges it. In Forge's
# own repo that base checkout is the Forge to install, so close and the check fingerprint alike.
WORKFLOW = """\
# Generated by forge sync for Forge <version>; forge sync rewrites it.
name: forge

on:
  pull_request:
  pull_request_target:

permissions:
  contents: read

jobs:
  tests:
    # Each event runs one of the two jobs. The skipped one takes another name, because a
    # skipped job would otherwise pass a required check of the same name.
    if: github.event_name == 'pull_request'
    name: ${{ github.event_name == 'pull_request' && 'tests' || 'tests (other event)' }}
    runs-on: ubuntu-latest
<tests-timeout>    steps:
      - uses: actions/checkout@v7
      - uses: astral-sh/setup-uv@v6
<node>      - run: <test>

  forge-pr-check:
    if: github.event_name == 'pull_request_target'
    name: ${{ github.event_name == 'pull_request_target' && 'forge-pr-check' || 'forge-pr-check (other event)' }}
    runs-on: ubuntu-latest
    steps:
      # The base branch's code and forge.toml; the pull request's commits are only data.
      - uses: actions/checkout@v7
        with:
          ref: ${{ github.event.pull_request.base.sha }}
          fetch-depth: 0
      - uses: astral-sh/setup-uv@v6
      - env:
          PR: ${{ github.event.pull_request.number }}
          BASE_SHA: ${{ github.event.pull_request.base.sha }}
          HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        run: |
          git fetch --no-tags origin "refs/pull/$PR/head"
          test "$(git rev-parse FETCH_HEAD)" = "$HEAD_SHA"
<choose>      - run: <install>
      - env:
          BASE_SHA: ${{ github.event.pull_request.base.sha }}
          HEAD_SHA: ${{ github.event.pull_request.head.sha }}
          HEAD_REF: ${{ github.event.pull_request.head.ref }}
        run: forge hook pr-check --base "$BASE_SHA" --head "$HEAD_SHA" --branch "$HEAD_REF"
"""

# A client's check runs the Forge release its default branch pins. A pull request that changes
# that pin (an upgrade) is checked by the release it pins instead, installed from Forge's own
# repo by its tag. The pin is read through git and parsed as TOML, and must look like a release
# before it is used; nothing from the pull request runs.
CHOOSE = r"""          pin() {
            git show "$1:forge.toml" | python3 -c '
          import sys, tomllib
          try:
              print(tomllib.load(sys.stdin.buffer).get("version", ""))
          except tomllib.TOMLDecodeError as problem:
              sys.exit(f"forge.toml in this pull request is not valid TOML: {problem}. Fix it, then push again.")'
          }
          release=$(pin "$HEAD_SHA")
          if [ "$release" = "$(pin "$(git merge-base "$BASE_SHA" "$HEAD_SHA")")" ]; then
            release="<version>"
          elif [[ ! "$release" =~ ^v?[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "This pull request sets Forge's version in forge.toml to \"$release\", which isn't a Forge release such as v1.2.0. Set it to a Forge release, then push again." >&2
            exit 1
          fi
          echo "FORGE_RELEASE=$release" >> "$GITHUB_ENV"
"""


def ships(top: Path, cfg: dict[str, Any]) -> dict[str, str]:
    from forge import sync

    node = ""
    if (top / "package.json").is_file():
        node = "      - uses: actions/setup-node@v7\n"
        version_file = next((name for name in (".nvmrc", ".node-version")
                             if (top / name).is_file()), None)
        if version_file:
            node += f"        with:\n          node-version-file: {version_file}\n"
        else:
            package = json.loads(sync.read(top / "package.json"))
            version = package.get("engines", {}).get("node")
            if isinstance(version, str) and version.strip():
                node += f"        with:\n          node-version: {json.dumps(version)}\n"
    source = cfg.get("repo") == "forge-source"
    workflow = (WORKFLOW.replace("<choose>", "" if source else CHOOSE)
                .replace("<version>", cfg["version"])
                .replace("<install>", "uv tool install ." if source
                         else sync.install_line("${FORGE_RELEASE#v}"))
                .replace("<tests-timeout>", "    timeout-minutes: 10\n"
                         if cfg.get("repo") == "client" and (top / "package.json").is_file()
                         else "")
                .replace("<node>", node)
                .replace("<test>", json.dumps(cfg["test"])))
    if "tests" not in cfg.get("checks", []):
        start = workflow.index("  tests:\n")
        end = workflow.index("  forge-pr-check:\n")
        workflow = workflow[:start] + workflow[end:]
    return {WORKFLOW_PATH: workflow}


def pr_check(args: argparse.Namespace) -> int:
    # The workflow runs: forge hook pr-check --base <sha> --head <sha> --branch <head branch>
    given = dict(zip(args.args[::2], args.args[1::2]))
    if len(args.args) != 6 or set(given) != {"--base", "--head", "--branch"}:
        repo.refuse(REFUSALS["usage"])
    base, head, branch = given["--base"], given["--head"], given["--branch"]
    if not branch.startswith(("task/", "fix/", "story/", "forge/")):
        print("Forge didn't start this branch, so it checks nothing here; the repo's own CI and "
              "review apply.")
        return 0
    top = repo.root()
    cfg = repo.config(top)  # the base checkout's forge.toml, never the head's
    item, state = _started(top, head, branch)
    changed = repo.git("diff", "--name-only", f"{base}...{head}", cwd=top).splitlines()
    if "/" not in item:
        missing = [line for line, key in (("Why:", "why"), ("Done when:", "done_when"))
                   if not str(state.get(key) or "").strip()]
        if missing:
            repo.refuse(REFUSALS["fix_line"], branch=branch, line=" or ".join(missing))
        problem = "" if state.get("allow_large") else promote_problem(changed, cfg["interfaces"])
        if problem:
            repo.refuse(REFUSALS["promote"], branch=branch, problem=problem, fix=item)
    try:
        story = importlib.import_module("forge.story")
    except ModuleNotFoundError as exc:
        if exc.name != "forge.story":
            raise
        # ponytail: STORY builds story.py in parallel; its story-doc checks run once it lands.
        story = None
    doc_problem = story.check_pr_docs(top, head, changed) if story else None
    if doc_problem:
        repo.refuse(REFUSALS["story_doc"], problem=doc_problem)
    result = state.get("review")
    if not (isinstance(result, dict) and isinstance(result.get("findings"), list)
            and isinstance(result.get("dismissals"), list)):
        problem = "missing"
    elif not _on_branch(top, str(result.get("commit", "")), head):
        problem = "for a commit that isn't part of this branch"
    elif result.get("changed") != review.fingerprint(head, item, top, state, base):
        problem = "out of date: the product files or what the change must do changed after it"
    elif review.blocking(result):
        problem = "blocked by serious findings no one fixed or dismissed"
    else:
        print(f"forge-pr-check passed for {branch}.")
        return 0
    repo.refuse(REFUSALS["not_reviewed"], branch=branch, problem=problem, item=item)


def promote_problem(changed: list[str], interfaces: list[str]) -> str:
    """Why a fix must become a story, or "": it touches an interfaces path, or more than five code
    files. Markdown, .factory/ and plans/ never count."""
    code = [path for path in changed
            if not path.lower().endswith(".md") and not path.startswith(review.BOOKKEEPING)]
    for path in code:
        # "/" + path lets "**/routes/**" match a top-level routes/ folder too.
        if any(fnmatch(path, pattern) or fnmatch("/" + path, pattern) for pattern in interfaces):
            return f"changes the interface path {path}"
    if len(code) > CODE_LIMIT:
        return f"changes {len(code)} code files, over the limit of {CODE_LIMIT}"
    return ""


def _on_branch(top: Path, commit: str, head: str) -> bool:
    """The reviewed commit is the head or one of its ancestors. It is read from the head, so it
    must look like a commit id before it goes near git."""
    return bool(re.fullmatch(r"[0-9a-f]{40}|[0-9a-f]{64}", commit)) and repo.run(
        "git", "merge-base", "--is-ancestor", commit, head, cwd=top).returncode == 0


def _started(top: Path, head: str, branch: str) -> tuple[str, dict[str, Any]]:
    """The task or fix whose state at head names this branch."""
    # ponytail: reads every task and fix state at the head, one git call each; batch them
    # (git cat-file --batch) when a repo holds thousands.
    listing = repo.git("ls-tree", "-r", "-z", "--name-only", head, "--", ".factory/stories",
                       ".factory/fixes", cwd=top)
    for path in listing.split("\0"):
        match = re.fullmatch(r"\.factory/(?:stories/([^/]+)/tasks/([^/]+)|fixes/([^/]+))\.json",
                             path)
        if not match:
            continue
        try:
            state = json.loads(repo.git("show", f"{head}:{path}", cwd=top))
        except ValueError:
            continue
        if isinstance(state, dict) and state.get("branch") == branch:
            return (f"{match[1]}/{match[2]}" if match[1] else match[3]), state
    repo.refuse(REFUSALS["not_started"], branch=branch)


COMMANDS = [{
    "words": "hook pr-check", "run": "pr_check", "changes_state": False,
    "help": "The required forge-pr-check, run from the base branch",
    "args": [], "position": 290,
    "listing": "| `forge hook pr-check` | The required `forge-pr-check`, run in CI from the base branch |",
}]
