"""forge sync: the adapter files for Claude Code and Codex, the CI workflow and the git hook shims.

The Markdown lives in templates/; the rest is inline here. AGENTS.md, CLAUDE.md, both host hook
files and .codex/config.toml are merged: everything in them that isn't Forge's stays as it is.
A git hook that was there before Forge is kept as <hook>.pre-forge and runs first.
"""
from __future__ import annotations

import argparse
import json
import re
import tomllib
from pathlib import Path
from typing import Any

from forge import repo

REFUSALS = {
    "outside": ("{path} leads outside this repo, so Forge won't write through it; remove that link.",
                "forge sync"),
    "cant_merge": ("{path} can't be merged ({problem}); fix it by hand.", "forge sync"),
    "bad_block": ("{path} has a broken Forge block; keep one <!-- forge:begin --> line and, after "
                  "it, one <!-- forge:end --> line.", "forge sync"),
    "hook_link": ("{path} links to a file outside this repo's .git folder, so Forge won't write "
                  "through it; put the hook itself there instead of the link.", "forge sync"),
    "hook_kept": ("{path} and {kept} both hold a hook that isn't Forge's; combine them into {kept} "
                  "by hand and delete {path}.", "forge sync"),
}

TEMPLATES = Path(__file__).with_name("templates")
BEGIN, END = "<!-- forge:begin -->", "<!-- forge:end -->"
WORKFLOW_PATH = ".github/workflows/forge.yml"
# A Forge host hook command: v1's, or the copied-in Forge's ("$(git rev-parse ...)/forge" hook x).
FORGE_COMMAND = re.compile(r'forge"? hook ')


def command(hook: str) -> str:
    """A host hook command that fails closed (decision 0038, ported).

    If forge can't launch, the inner guard turns that into exit 2; if sh itself can't, the outer
    one does. Exit 2 is the code both hosts treat as blocking.
    """
    return f"sh -c 'forge hook {hook} || exit 2' || exit 2"


# Each host's hook file: event -> (the tools it matches, or None for all; the forge hook it runs).
HOSTS = {
    ".claude/settings.json": {"SessionStart": (None, "context"), "PreToolUse": ("Bash", "deny"),
                              "PostToolUse": ("ExitPlanMode|AskUserQuestion", "approval")},
    ".codex/hooks.json": {"SessionStart": (None, "context"), "PreToolUse": ("Bash", "deny"),
                          "PostToolUse": ("request_user_input", "approval")},
}

CODEX_CONFIG = """\
# Codex runs the project hooks in .codex/hooks.json only with this on; forge sync keeps it on.
[features]
hooks = true
"""
FEATURES = re.compile(r"^[ \t]*\[[ \t]*features[ \t]*\][ \t]*(#.*)?$", re.M)
TABLE = re.compile(r"^[ \t]*\[", re.M)

SHIM_MARK = "# Generated by forge sync"
# The hook that was there before Forge runs first, with the same arguments and input.
SHIM = """\
#!/bin/sh
# Generated by forge sync for Forge <version>; forge sync rewrites it. It is never committed.
if [ -x "$0.pre-forge" ]; then
  input=$(mktemp) || exit 1
  cat > "$input"
  "$0.pre-forge" "$@" < "$input" || { status=$?; rm -f "$input"; exit "$status"; }
  exec < "$input"
  rm -f "$input"
fi
command -v forge >/dev/null 2>&1 && exec forge hook <hook> "$@"
echo "Forge isn't installed, so git can't check this <what>." >&2
echo "Next: <install>" >&2
exit 1
"""

# tests checks the pull request's own code. forge-pr-check runs from the base branch
# (pull_request_target), so a pull request can't change the check that judges it. In Forge's
# own repo that base checkout is the Forge to install, so close and the check fingerprint alike.
WORKFLOW = """\
# Generated by forge sync for Forge <version>; forge sync rewrites it.
name: forge

on:
  pull_request:
  pull_request_target:

permissions:
  contents: read

jobs:
  tests:
    # Each event runs one of the two jobs. The skipped one takes another name, because a
    # skipped job would otherwise pass a required check of the same name.
    if: github.event_name == 'pull_request'
    name: ${{ github.event_name == 'pull_request' && 'tests' || 'tests (other event)' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: astral-sh/setup-uv@v6
      - run: <test>

  forge-pr-check:
    if: github.event_name == 'pull_request_target'
    name: ${{ github.event_name == 'pull_request_target' && 'forge-pr-check' || 'forge-pr-check (other event)' }}
    runs-on: ubuntu-latest
    steps:
      # The base branch's code and forge.toml; the pull request's commits are only data.
      - uses: actions/checkout@v7
        with:
          ref: ${{ github.event.pull_request.base.sha }}
          fetch-depth: 0
      - uses: astral-sh/setup-uv@v6
      - run: <install>
      - env:
          PR: ${{ github.event.pull_request.number }}
          BASE_SHA: ${{ github.event.pull_request.base.sha }}
          HEAD_SHA: ${{ github.event.pull_request.head.sha }}
          HEAD_REF: ${{ github.event.pull_request.head.ref }}
        run: |
          git fetch --no-tags origin "refs/pull/$PR/head"
          test "$(git rev-parse FETCH_HEAD)" = "$HEAD_SHA"
          forge hook pr-check --base "$BASE_SHA" --head "$HEAD_SHA" --branch "$HEAD_REF"
"""


def install_line(version: str) -> str:
    """The command that installs the pinned Forge (the pin refusal's own Next line)."""
    return repo.REFUSALS["pin"][1].format(pinned="v" + version.removeprefix("v"))


def read(path: Path) -> str:
    return path.read_text(encoding="utf-8") if path.is_file() else ""


def write_file(top: Path, rel: str, text: str) -> None:
    """Write a repo file with LF line endings, never through a link that leads outside the repo."""
    path = top / rel
    if not path.resolve().is_relative_to(top.resolve()):
        repo.refuse(REFUSALS["outside"], path=rel)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(text.encode("utf-8"))


def _block(top: Path, rel: str, template: str) -> str:
    """The file with its Forge block replaced, or appended when it has none."""
    text = read(top / rel)
    block = f"{BEGIN}\n{(TEMPLATES / template).read_text(encoding='utf-8').rstrip()}\n{END}"
    start, end = text.find(BEGIN), text.find(END)
    if start == end == -1:
        return f"{text.rstrip()}\n\n{block}\n" if text.strip() else f"{block}\n"
    if not 0 <= start < end or text.count(BEGIN) + text.count(END) != 2:
        repo.refuse(REFUSALS["bad_block"], path=rel)
    return text[:start] + block + text[end + len(END):]


def _hooks(top: Path, rel: str, events: dict[str, tuple[str | None, str]]) -> str:
    """The host's hook file with Forge's entries replaced (old Forge's too); the rest stays."""
    text = read(top / rel)
    try:
        data = json.loads(text) if text.strip() else {}
        hooks = data.setdefault("hooks", {})
        for event in list(hooks):
            groups = [{**group, "hooks": kept} for group in hooks[event]
                      if (kept := [hook for hook in group.get("hooks", [])
                                   if not FORGE_COMMAND.search(hook.get("command", ""))])]
            if groups:
                hooks[event] = groups
            else:
                del hooks[event]
        for event, (matcher, hook) in events.items():
            group: dict[str, Any] = {"hooks": [{"type": "command", "command": command(hook)}]}
            hooks.setdefault(event, []).append({"matcher": matcher, **group} if matcher else group)
    except (ValueError, AttributeError, TypeError) as exc:
        repo.refuse(REFUSALS["cant_merge"], path=rel, problem=exc)
    return json.dumps(data, indent=2) + "\n"


def _codex_config(top: Path) -> str:
    """.codex/config.toml with Codex's project hooks on; every other setting stays as it is."""
    rel = ".codex/config.toml"
    text = read(top / rel)
    if not text.strip():
        return CODEX_CONFIG
    try:
        data = tomllib.loads(text)
    except tomllib.TOMLDecodeError as exc:
        repo.refuse(REFUSALS["cant_merge"], path=rel, problem=exc)
    features = data.get("features")
    if isinstance(features, dict) and features.get("hooks") is True:
        return text
    # ponytail: stdlib has no TOML writer, so edit one line as text, then require the result to
    # parse to the same settings plus hooks = true. Anything else (features as dotted keys or an
    # inline table, a quoted or multi-line hooks value) refuses instead of guessing.
    merged, header = "", FEATURES.search(text)
    if features is None:
        merged = f"{text.rstrip()}\n\n{CODEX_CONFIG}"
    elif isinstance(features, dict) and header:
        after = TABLE.search(text, header.end())
        end = after.start() if after else len(text)
        table = text[header.end():end]
        line = re.search(r"^[ \t]*hooks[ \t]*=.*$", table, re.M)
        table = (table[:line.start()] + "hooks = true" + table[line.end():] if line
                 else "\nhooks = true" + table)
        merged = text[:header.end()] + table + text[end:]
    try:
        safe = bool(merged) and tomllib.loads(merged) == {
            **data, "features": {**(features or {}), "hooks": True}}
    except tomllib.TOMLDecodeError:
        safe = False
    if not safe:
        repo.refuse(REFUSALS["cant_merge"], path=rel,
                    problem="Forge can't safely set hooks = true in its [features] table")
    return merged


def files(top: Path, cfg: dict[str, Any]) -> dict[str, str]:
    """Every committed file sync writes: repo-relative path -> its text for this checkout."""
    skill = (TEMPLATES / "skill.md").read_text(encoding="utf-8")
    workflow = (WORKFLOW.replace("<version>", cfg["version"])
                .replace("<install>", "uv tool install ." if cfg.get("repo") == "forge-source"
                         else install_line(cfg["version"]))
                .replace("<test>", json.dumps(cfg["test"])))
    return {
        "AGENTS.md": _block(top, "AGENTS.md", "adapters/AGENTS.md"),
        "CLAUDE.md": _block(top, "CLAUDE.md", "adapters/CLAUDE.md"),
        **{rel: _hooks(top, rel, events) for rel, events in HOSTS.items()},
        ".claude/skills/forge/SKILL.md": skill,
        ".codex/skills/forge/SKILL.md": skill,
        # Discovery's worked example, question bank and call script, opened only when needed.
        **{f"{host}/skills/forge/fde.md": (TEMPLATES / "fde.md").read_text(encoding="utf-8")
           for host in (".claude", ".codex")},
        # The test-audit skill (MIT, with its NOTICE) that workers and reviewers use for tests.
        **{f"{host}/skills/test-audit/{path.name}": path.read_text(encoding="utf-8")
           for host in (".claude", ".codex")
           for path in sorted((TEMPLATES / "skills" / "test-audit").glob("*.md"))},
        # Claude Code only: the Remote Control session it starts is a Claude feature.
        ".claude/skills/remote-approval/SKILL.md":
            (TEMPLATES / "skills" / "remote-approval" / "SKILL.md").read_text(encoding="utf-8"),
        ".codex/config.toml": _codex_config(top),
        WORKFLOW_PATH: workflow,
    }


def shims(top: Path, cfg: dict[str, Any]) -> dict[Path, str]:
    """The two git hook shims, in the hooks folder every worktree shares."""
    # Asked from the checkout's top: git gives core.hooksPath when set, and resolves a relative
    # one from the worktree's root, where git runs its hooks (checked with git 2.47).
    folder = Path(repo.git("rev-parse", "--path-format=absolute", "--git-path", "hooks", cwd=top))
    return {folder / hook: SHIM.replace("<version>", cfg["version"]).replace("<hook>", hook)
            .replace("<what>", what).replace("<install>", install_line(cfg["version"]))
            for hook, what in (("pre-commit", "commit"), ("pre-push", "push"))}


def write(top: Path, cfg: dict[str, Any]) -> list[str]:
    """Write the files that differ from what sync makes; returns them. Never on the default branch."""
    wanted = files(top, cfg)
    changed = [rel for rel, text in wanted.items() if read(top / rel) != text]
    if changed:
        repo._work_branch(top)  # the shared rule: a born default branch or a detached HEAD refuses
    for rel in changed:
        write_file(top, rel, wanted[rel])
    return changed


def install_shims(top: Path, cfg: dict[str, Any]) -> bool:
    """Install the git hook shims; returns whether any changed. They are never committed.

    A hook there that isn't Forge's moves to <hook>.pre-forge, and the shim runs it first.
    """
    common = Path(repo.git("rev-parse", "--path-format=absolute", "--git-common-dir", cwd=top))
    changed = False
    for path, text in shims(top, cfg).items():
        if path.is_symlink() and not path.resolve().is_relative_to(common.resolve()):
            repo.refuse(REFUSALS["hook_link"], path=path)
        current = read(path)
        if current != text:
            if (path.exists() or path.is_symlink()) and SHIM_MARK not in current:
                kept = path.with_name(f"{path.name}.pre-forge")
                if kept.exists() or kept.is_symlink():
                    repo.refuse(REFUSALS["hook_kept"], path=path, kept=kept)
                path.rename(kept)
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(text.encode("utf-8"))
            changed = True
        path.chmod(0o755)
    return changed


def sync(args: argparse.Namespace) -> None:
    top = repo.root()
    cfg = repo.config(top)
    changed = write(top, cfg)
    for rel in changed:
        print(f"Wrote {rel}")
    if install_shims(top, cfg):
        print("Installed the git hooks that check each commit and push.")
    elif not changed:
        print(f"Nothing to change: the adapters and git hooks already match Forge {cfg['version']}.")
