"""forge sync: the adapter files for Claude Code and Codex, the CI workflow and the git hook shims.

The Markdown lives in templates/; the rest is inline here. AGENTS.md, both host hook
files and .codex/config.toml are merged: everything in them that isn't Forge's stays as it is.
A git hook that was there before Forge is kept as <hook>.pre-forge and runs first.
"""
from __future__ import annotations

import argparse
import ast
import importlib
import json
import pkgutil
import re
import shlex
import subprocess
import sys
import tempfile
import tomllib
from pathlib import Path
from typing import Any

import forge
from forge import githooks, prcheck, repo, roles

COMMANDS = [{
    "words": "sync", "run": "sync", "changes_state": True,
    "help": "Write the generated adapter files and git hooks for the pinned version",
    "args": [], "position": 20,
    "listing": "| `forge sync` | Writes the generated files for both hosts, the CI workflow and the git hooks |",
}]

REFUSALS = {
    "outside": ("{path} leads outside this repo, so Forge won't write through it; remove that link.",
                "forge sync"),
    "cant_merge": ("{path} can't be merged ({problem}); fix it by hand.", "forge sync"),
    "bad_block": ("{path} has a broken Forge block; keep one <!-- forge:begin --> line and, after "
                  "it, one <!-- forge:end --> line.", "forge sync"),
    "hook_link": ("{path} links to a file outside this repo's .git folder, so Forge won't write "
                  "through it; put the hook itself there instead of the link.", "forge sync"),
    "hook_kept": ("{path} and {kept} both hold a hook that isn't Forge's; combine them into {kept} "
                  "by hand and delete {path}.", "forge sync"),
}

TEMPLATES = Path(__file__).with_name("templates")
SOURCE = Path(__file__).resolve().parents[2]
BEGIN, END = "<!-- forge:begin -->", "<!-- forge:end -->"
WORKFLOW_PATH = prcheck.WORKFLOW_PATH
# A Forge host hook command: v1's, or the copied-in Forge's ("$(git rev-parse ...)/forge" hook x).
FORGE_COMMAND = re.compile(r'forge"? hook ')


LAUNCHER = ".forge/hooks.sh"


def command(hook: str) -> str:
    """A host hook command that fails closed (decision 0038, ported), with forge from the launcher.

    If forge can't launch, the inner guard turns that into exit 2; if sh itself can't, the outer
    one does. Exit 2 is the code both hosts treat as blocking.
    """
    return (f"sh -c '. \"$(git rev-parse --show-toplevel)/{LAUNCHER}\" && forge hook {hook} || exit 2'"
            " || exit 2")


# Both hosts' hooks source this, since a host may run hooks with a PATH that lacks forge's install
# folder (Codex does). Each fallback keeps a machine without forge unblocked.
LAUNCHER_TEXT = """\
# Generated by forge sync for Forge v<version>; forge sync rewrites it. Host hooks source it.
for folder in /usr/local/bin /opt/homebrew/bin "$HOME/.local/bin" "$XDG_BIN_HOME" "$UV_TOOL_BIN_DIR"; do
  [ -d "$folder" ] && PATH="$folder:$PATH"
done
export PATH
if command -v forge >/dev/null 2>&1; then :
elif command -v uvx >/dev/null 2>&1; then
  forge() { uvx -q --from git+https://github.com/knacklabs/symphony-forge@v<version> forge "$@"; }
else
  forge() { echo "Forge isn't installed, so this hook can't run; install it with <install>, then run forge doctor." >&2; return 2; }
fi
"""


def launcher(cfg: dict[str, Any]) -> str:
    version = cfg["version"].removeprefix("v")
    return LAUNCHER_TEXT.replace("<install>", install_line(version)).replace("<version>", version)


HOSTS = githooks.HOSTS

CODEX_CONFIG = """\
# Codex runs the project hooks in .codex/hooks.json only with this on; forge sync keeps it on.
[features]
hooks = true
"""
# Forge gives Codex full access; forge.toml's models and the host choose the model, so an old pin goes.
FULL_ACCESS = {"sandbox_mode": "danger-full-access", "approval_policy": "never"}
PINS = ("model", "model_reasoning_effort")
# A role that leaves its model out runs on these before the session's, so they go too.
AGENT_PINS = ("default_subagent_model", "default_subagent_reasoning_effort")
AGENTS = re.compile(r"^[ \t]*\[[ \t]*agents[ \t]*\][ \t]*(#.*)?$", re.M)
FEATURES = re.compile(r"^[ \t]*\[[ \t]*features[ \t]*\][ \t]*(#.*)?$", re.M)
TABLE = re.compile(r"^[ \t]*\[", re.M)

shims = githooks.shims

# Every story and fix adds to the roadmap, so git merges it with Forge's rule instead of by line.
ROADMAP_RULE = "plans/roadmap.json merge=forge-roadmap"
RANK = {"pending": 0, "done": 2}  # planning, started and the rest sit between the two

def install_line(version: str) -> str:
    """The command that installs the pinned Forge (the pin refusal's own Next line)."""
    return repo.REFUSALS["pin"][1].format(pinned="v" + version.removeprefix("v"))


def read(path: Path) -> str:
    return path.read_text(encoding="utf-8") if path.is_file() else ""


def write_file(top: Path, rel: str, text: str) -> None:
    """Write a repo file with LF line endings, never through a link that leads outside the repo."""
    path = top / rel
    if not path.resolve().is_relative_to(top.resolve()):
        repo.refuse(REFUSALS["outside"], path=rel)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(text.encode("utf-8"))


def _span(text: str, rel: str) -> tuple[int, int]:
    """Where the Forge block starts and ends in the text, or (-1, -1) when there is none."""
    start, end = text.find(BEGIN), text.find(END)
    if start == end == -1:
        return -1, -1
    if not 0 <= start < end or text.count(BEGIN) + text.count(END) != 2:
        repo.refuse(REFUSALS["bad_block"], path=rel)
    return start, end + len(END)


def _block(top: Path, rel: str, template: str) -> str:
    """The file with its Forge block replaced, or appended when it has none."""
    text = read(top / rel)
    block = f"{BEGIN}\n{(TEMPLATES / template).read_text(encoding='utf-8').rstrip()}\n{END}"
    start, end = _span(text, rel)
    if start == -1:
        return f"{text.rstrip()}\n\n{block}\n" if text.strip() else f"{block}\n"
    return text[:start] + block + text[end:]


def _claude(top: Path) -> str:
    """CLAUDE.md without the Forge block an older Forge wrote; "" means delete it.

    Claude Code reads AGENTS.md by itself when there is no CLAUDE.md, so a CLAUDE.md whose every
    line is already in AGENTS.md goes. One with a line of its own stays, and keeps an @AGENTS.md
    line, since Claude Code reads it instead.
    """
    text = read(top / "CLAUDE.md")
    start, end = _span(text, "CLAUDE.md")
    rest = (text if start == -1 else text[:start] + text[end:]).strip()
    agents = {line.strip() for line in read(top / "AGENTS.md").splitlines()}
    if all(line in agents for line in map(str.strip, rest.splitlines())
           if line and line != "@AGENTS.md"):
        return ""
    return rest + "\n" if re.search(r"^@AGENTS\.md[ \t]*$", rest, re.M) else f"{rest}\n\n@AGENTS.md\n"


def _hooks(top: Path, rel: str, events: dict[str, tuple[str | None, str]],
           allow: list[str]) -> str:
    """The host's hook file with Forge's entries replaced (old Forge's too) and the tools in allow
    added to its allow list; the rest stays."""
    text = read(top / rel)
    try:
        data = json.loads(text) if text.strip() else {}
        hooks = data.setdefault("hooks", {})
        for event in list(hooks):
            groups = [{**group, "hooks": kept} for group in hooks[event]
                      if (kept := [hook for hook in group.get("hooks", [])
                                   if not FORGE_COMMAND.search(hook.get("command", ""))])]
            if groups:
                hooks[event] = groups
            else:
                del hooks[event]
        for event, (matcher, hook) in events.items():
            group: dict[str, Any] = {"hooks": [{"type": "command", "command": command(hook)}]}
            hooks.setdefault(event, []).append({"matcher": matcher, **group} if matcher else group)
        if allow:
            allowed = data.setdefault("permissions", {}).setdefault("allow", [])
            allowed += [tool for tool in allow if tool not in allowed]
    except (ValueError, AttributeError, TypeError) as exc:
        repo.refuse(REFUSALS["cant_merge"], path=rel, problem=exc)
    return json.dumps(data, indent=2) + "\n"


def _codex_config(top: Path) -> str:
    """.codex/config.toml with full access, no model pin (subagent defaults included) and Codex's
    project hooks on; every other setting stays as it is."""
    rel = ".codex/config.toml"
    text = read(top / rel)
    try:
        data = tomllib.loads(text)
    except tomllib.TOMLDecodeError as exc:
        repo.refuse(REFUSALS["cant_merge"], path=rel, problem=exc)
    features = data.get("features")
    wanted = {**{key: value for key, value in data.items() if key not in PINS}, **FULL_ACCESS,
              "features": {**(features if isinstance(features, dict) else {}), "hooks": True}}
    if isinstance(data.get("agents"), dict):
        wanted["agents"] = {key: value for key, value in data["agents"].items()
                            if key not in AGENT_PINS}
    # == alone takes hooks = 1 for true, so hooks must be the boolean itself.
    exact = lambda parsed: parsed == wanted and parsed["features"]["hooks"] is True  # noqa: E731
    if exact(data):
        return text
    # ponytail: stdlib has no TOML writer, so edit lines as text, then require the result to parse
    # to exactly the wanted settings. Anything else (features as dotted keys or an inline table, a
    # setting's line inside a multi-line value) refuses instead of guessing.
    first = TABLE.search(text)
    top, rest = (text[:first.start()], text[first.start():]) if first else (text, "")
    for key in PINS:
        top = re.sub(rf"^[ \t]*{key}[ \t]*=.*\n?", "", top, count=1, flags=re.M)
    missing = ""
    for key, value in FULL_ACCESS.items():
        line = re.search(rf"^[ \t]*{key}[ \t]*=.*$", top, re.M)
        if line:
            top = top[:line.start()] + f'{key} = "{value}"' + top[line.end():]
        else:
            missing += f'{key} = "{value}"\n'
    if missing:
        top = (f"{top.rstrip()}\n" if top.strip() else "") + missing + ("\n" if rest else "")
    text = top + rest
    header = AGENTS.search(text)
    if header:
        after = TABLE.search(text, header.end())
        end = after.start() if after else len(text)
        table = text[header.end():end]
        for key in AGENT_PINS:
            table = re.sub(rf"^[ \t]*{key}[ \t]*=.*\n?", "", table, count=1, flags=re.M)
        text = text[:header.end()] + table + text[end:]
    merged, header = "", FEATURES.search(text)
    if isinstance(features, dict) and features.get("hooks") is True:
        merged = text
    elif features is None:
        merged = f"{text.rstrip()}\n\n{CODEX_CONFIG}"
    elif isinstance(features, dict) and header:
        after = TABLE.search(text, header.end())
        end = after.start() if after else len(text)
        table = text[header.end():end]
        line = re.search(r"^[ \t]*hooks[ \t]*=.*$", table, re.M)
        table = (table[:line.start()] + "hooks = true" + table[line.end():] if line
                 else "\nhooks = true" + table)
        merged = text[:header.end()] + table + text[end:]
    try:
        safe = bool(merged) and exact(tomllib.loads(merged))
    except tomllib.TOMLDecodeError:
        safe = False
    if not safe:
        repo.refuse(REFUSALS["cant_merge"], path=rel,
                    problem="Forge can't safely set Codex's full access and hooks in it")
    return merged


def ships(top: Path, cfg: dict[str, Any]) -> dict[str, str]:
    text = read(top / ".gitattributes")
    if ROADMAP_RULE not in text.splitlines():
        text = f"{text.rstrip()}\n{ROADMAP_RULE}\n" if text.strip() else f"{ROADMAP_RULE}\n"
    return {".gitattributes": text, LAUNCHER: launcher(cfg)}


def merge_roadmap(base: str, ours: str, theirs: str) -> int:
    """Git's merge driver for the roadmap: writes the merge over ours; 1 leaves git's conflict.

    Every item on either side stays, in ours' order then theirs' new ones. When both sides changed
    an item, the one whose status is further along wins, otherwise ours.
    """
    try:
        old, mine, other = (json.loads(Path(path).read_text(encoding="utf-8") or "{}")
                            for path in (base, ours, theirs))
        was = {item["key"]: item for item in old.get("items", [])}
        items = {item["key"]: item for item in mine["items"]}
        rank = lambda entry: RANK.get(entry.get("status"), 1)  # noqa: E731
        for item in other["items"]:
            key, kept = item["key"], items.get(item["key"])
            if kept is None or kept == was.get(key) or (item != was.get(key) and rank(item) > rank(kept)):
                items[key] = item
        # The other top-level fields: theirs only where ours left the base's value alone.
        merged = {**mine, **{name: value for name, value in other.items()
                             if name != "items" and mine.get(name) == old.get(name)}}
        merged["items"] = list(items.values())
    except (ValueError, KeyError, TypeError, AttributeError):
        return 1
    Path(ours).write_bytes((json.dumps(merged, indent=2) + "\n").encode("utf-8"))
    return 0


def _synced_text(source: str, packaged: str) -> str:
    """Read the checkout's copy in editable installs, or the bundled copy in built installs."""
    checked_in = SOURCE / source
    return (checked_in if checked_in.is_file() else TEMPLATES / packaged).read_text(encoding="utf-8")


def files(top: Path, cfg: dict[str, Any]) -> dict[str, str]:
    """Every committed file sync writes: repo-relative path -> its text for this checkout."""
    wanted: dict[str, str] = {}
    for info in pkgutil.iter_modules(forge.__path__):
        if info.ispkg:
            continue
        source = Path(info.module_finder.path) / f"{info.name}.py"
        if not any(isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)) and node.name == "ships"
                   for node in ast.parse(source.read_text(encoding="utf-8")).body):
            continue
        module = importlib.import_module(f"forge.{info.name}")
        for rel, text in module.ships(top, cfg).items():
            if rel in wanted:
                raise ValueError(f"shipped twice: {rel}")
            wanted[rel] = text
    return wanted


def synced(top: Path, cfg: dict[str, Any], base: str, head: str, paths: list[str]) -> set[str]:
    """The paths whose content at head ("" for the index) is exactly what forge sync writes over
    the base commit's files with this config, so a fix's size doesn't count them."""
    def show(rev: str, path: str) -> bytes:
        done = subprocess.run(["git", "show", f"{rev}:{path}"], cwd=top, capture_output=True)
        return b"" if done.returncode else done.stdout  # a missing file, as sync's "" deletes it

    # ponytail: unpacks the whole base tree once per oversized fix; list sync's inputs if it's slow.
    with tempfile.TemporaryDirectory() as tmp:
        tar = subprocess.run(["git", "archive", base], cwd=top, capture_output=True, check=True)
        subprocess.run(["tar", "-x", "-C", tmp], input=tar.stdout, check=True)
        wanted = files(Path(tmp), cfg)
    return {path for path in paths
            if path in wanted and show(head, path) == wanted[path].encode("utf-8")}


def command_page() -> str:
    """The source repo's command list, in the order shown by Forge's declarations."""
    commands = []
    for info in pkgutil.iter_modules(forge.__path__):
        if info.ispkg:
            continue
        source = Path(info.module_finder.path) / f"{info.name}.py"
        if not any(isinstance(node, ast.Assign) and any(
                isinstance(target, ast.Name) and target.id == "COMMANDS" for target in node.targets)
                   for node in ast.parse(source.read_text(encoding="utf-8")).body):
            continue
        module = importlib.import_module(f"forge.{info.name}")
        commands.extend(module.COMMANDS)
    rows = [command["listing"] for command in sorted(
        commands, key=lambda command: (command["position"], command["words"]))]
    return "# Forge commands\n\n| Command | What it does |\n|---|---|\n" + "\n".join(rows) + "\n"


def write(top: Path, cfg: dict[str, Any]) -> list[str]:
    """Write the files that differ from what sync makes; returns them. Never on the default branch."""
    wanted = files(top, cfg)
    changed = [rel for rel, text in wanted.items() if read(top / rel) != text]
    if changed:
        repo._work_branch(top)  # the shared rule: a born default branch or a detached HEAD refuses
        roles.refuse_foreign(top, changed)
    for rel in changed:
        if wanted[rel]:
            write_file(top, rel, wanted[rel])
        else:
            (top / rel).unlink()
    return changed


def install_shims(top: Path, cfg: dict[str, Any]) -> bool:
    """Install the git hook shims; returns whether any changed. They are never committed.

    A hook there that isn't Forge's moves to <hook>.pre-forge, and the shim runs it first.
    """
    common = Path(repo.git("rev-parse", "--path-format=absolute", "--git-common-dir", cwd=top))
    changed = False
    for path, text in shims(top, cfg).items():
        if path.is_symlink() and not path.resolve().is_relative_to(common.resolve()):
            repo.refuse(REFUSALS["hook_link"], path=path)
        current = read(path)
        if current != text:
            if (path.exists() or path.is_symlink()) and githooks.SHIM_MARK not in current:
                kept = path.with_name(f"{path.name}.pre-forge")
                if kept.exists() or kept.is_symlink():
                    repo.refuse(REFUSALS["hook_kept"], path=path, kept=kept)
                path.rename(kept)
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(text.encode("utf-8"))
            changed = True
        path.chmod(0o755)
    # The roadmap's merge driver runs this Forge's own code with the Python running it now.
    code = (f"import sys; sys.path.insert(0, {str(Path(__file__).resolve().parents[1])!r}); "
            "from forge.sync import merge_roadmap; sys.exit(merge_roadmap(*sys.argv[1:]))")
    driver = f"{shlex.quote(sys.executable)} -c {shlex.quote(code)} %O %A %B"
    current = repo.run("git", "config", "--get", "merge.forge-roadmap.driver", cwd=top).stdout
    if current.strip() != driver:
        repo.git("config", "merge.forge-roadmap.driver", driver, cwd=top)
        changed = True
    return changed


def sync(args: argparse.Namespace) -> None:
    top = repo.root()
    cfg = repo.config(top)
    changed = write(top, cfg)
    if cfg.get("repo") == "forge-source":
        page = command_page()
        if read(top / "docs/commands.md") != page:
            repo._work_branch(top)
            write_file(top, "docs/commands.md", page)
            changed.append("docs/commands.md")
    for rel in changed:
        print(f"Wrote {rel}")
    if install_shims(top, cfg):
        print("Installed the git hooks that check each commit and push.")
    elif not changed:
        print(f"Nothing to change: the adapters and git hooks already match Forge {cfg['version']}.")
